apiVersion: v1
kind: Service
metadata:
  name: presto
  labels:
    app.kubernetes.io/name: presto
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: presto
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
